### ISSUE TITLE
Handle 3rd-level deep nested objects

### ISSUE THREAD

**Issue by rozhok** [nerzh/slim_form_object#6]
So I have complex form: Owner who owns some Pets which do have several Photos.
I'd like to add multiple pets per owner and then add multiple photos per pet.

Currently we could only handle two levels-deep form.

**Comment by nerzh** [comment]
thanks for the you feedback!
now works recursively nesting objects with helper field_for with {sfo_nested:  true}
```ruby
= form_for(RegistrationFormObject.new, url: registration_path(resource_name)) do |f|
  = f.text_field 'user-first_name'
  = f.text_field 'user-last_name'
  = f.fields_for :user, {sfo_nested: true} do |n|
    = n.text_field 'address_user-phone'
    = n.fields_for :address_user, {sfo_nested: true} do |z|
      = z.text_field 'city-name'
        ...
```
